language: node_js
node_js:
  - '4'
sudo: required
cache:
  directories:
    - node_modules
env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-beta
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
    - env: ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-beta
    - env: ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-canary
before_install:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g npm@^3
  - npm install -g bower
  - npm install -g codeclimate-test-reporter
install:
  - npm install
  - bower install
script:
  - ember try $EMBER_TRY_SCENARIO test --skip-cleanup
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  code_climate:
    repo_token: cd4864af0d8f2a752bbb1013ccce2ad45df17162a0068a23a746bbdb8b568af3
after_script:
  - codeclimate-test-reporter < lcov.dat
